services:
  - type: web
    name: cmoc-inventory-api
    env: node
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy && npm run prisma:seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prod.db
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
